config/routes.rb
Rails.application.routes.draw do
  post 'users/image'
  root to: 'posts#index'
  resources :posts
  resources :tags
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: {message: "既に存在しているユーザー名です"}

  has_one_attached :image

  def email_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    params['name'] =  params['name'].presence || ""
    @tags = Tag.all
    @tag = Tag.find_by_name(params['name'])
    session[:tag_name] = params['name']
    if @tag.blank?
      @tag = Tag.create(name: params['name'])
    end
    from = Time.now - 300
    to = Time.now
    
    @post = Post.new
    @posts = @tag.posts.where(created_at: from..to).includes(user: {image_attachment: :blob})
  end


  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    tag_id = Tag.find_by_name(session[:tag_name]).id
    @post.tag_id = tag_id

    respond_to do |format|
      if @post.save
        broad_params = {}
        broad_params['content'] = @post.content
        broad_params['created'] = l(@post.created_at)
        broad_params['username'] = current_user.username
        broad_params['image'] = current_user.image.attached? ? url_for(current_user.image.variant(gravity: :center, resize:"40x40^", crop:"40x40+0+0").processed) : "/first.png"
        ActionCable.server.broadcast("tag_channel_#{session[:tag_name]}", broad_params)
        format.json { render json: @post , status: :created }
      else
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def post_params
      params["post"]["user_id"] = current_user.id
      params.require(:post).permit(:user_id, :tag_id, :content)
    end
end

app/controllers/users_controller.rb
require 'mini_magick'

class UsersController < ApplicationController
  before_action :authenticate_user!

  def image
    if image = params[:image]
      img = MiniMagick::Image.read(params[:image])

      img.combine_options do |i|
        i.resize("40x40^")
        i.gravity("center")
        i.crop("40x40+0+0")
      end

      current_user.image.attach(io: File.open(img.path), filename: current_user.id, content_type: img.mime_type)
    end

    redirect_to controller: 'posts', action: 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FiveminSns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<nav class="uk-navbar-container  uk-navbar-transparent" uk-navbar>
    <div class="uk-navbar-left">
        <a class="uk-navbar-item uk-logo" href="#">
          <img src="/logo.gif">
        </a>
    </div>

    <div class="uk-navbar-right">
      <div class="uk-nabvar-item">
        タグ：
        <a href="#modal-tag" class="uk-button uk-button-default uk-text-capitalize" uk-toggle>
        <% if @tag.name.present? %>
          <%= @tag.name %>
        <% else %>
          未選択
        <% end %>
        </a>
      </div>

      <a href="#modal-image" class="uk-navbar-item" uk-toggle>
      <% if current_user.image.attached? %>
        <%= image_tag current_user.image,
          class: "uk-border-circle"
        %>
      <% else %>
        <%= image_tag '/first.png', class: "uk-border-circle uk-margin-right" %>
      <% end %>
      </a>
    </div>
</nav>

<div id="modal-tag" class="uk-flex-top" uk-modal>
  <div class="uk-modal-dialog uk-margin-auto-vertical uk-padding">
    <%= form_with(url: root_path, local: true, method: "get") do |form| %>
      <%= form.text_field :name, class: "uk-input uk-form-width-medium", autocomplete: "on", list: "tags"  %>
      <datalist id="tags">
      <% @tags.each do |tag| %>
        <option><%= tag.name %></option>
      <% end %>
      </datalist>
      <button class="uk-button uk-button-default">選択</button>
    <% end %>
  </div>
</div>

<div id="modal-image" class="uk-flex-top" uk-modal>
  <div class="uk-modal-dialog uk-margin-auto-vertical uk-padding">
  <%= form_with(url: users_image_path, local: true) do |form| %>
    <div class="uk-margin">
      <div uk-form-custom="target: true">
        <%= form.file_field :image%>
        <input class="uk-input uk-form-width-medium" type="text" placeholder="画像を選択してください" disable>
      </div>
      <%= form.submit "決定", class: "uk-button uk-button-default"%>
    </div>
  <% end %>
  </div>
</div>

<div class="uk-container">

<%= form_with(model: @post ,class: "uk-panel") do |form| %>
  <div class="uk-margin">
    <%= form.text_area :content , class: "uk-textarea"%>
  </div>

  <div class="uk-margin">
    <%= form.submit "投稿", class: "uk-button uk-button-default uk-align-right"%>
  </div>
<% end %>

  <div id="posts">
  <% @posts.reverse.each do |post| %>
    <div class="uk-card uk-card-default">
      <div class="uk-card-header">
        <div class="uk-grid-small uk-flex-middle" uk-grid>
          <div class="uk-width-auto">
          <% if post.user.image.attached? %>
            <%= image_tag post.user.image,
              class: "uk-border-circle"
            %>
          <% else %>
            <%= image_tag '/first.png', class: "uk-border-circle"%>
          <% end %>
          </div>
          <div class="uk-width-expand">
              <p class="uk-margin-remove-bottom"><%= post.user.username %></p>
              <p class="uk-text-meta uk-margin-remove-top created"><%= l post.created_at %></p>
          </div>
        </div>
      </div>

      <div class="uk-card-body uk-padding-small">
        <p><%= post.content %></p>
      </div>
    </div>
  <% end %>
  </div>
</div>

<div id='post-template' class="uk-card uk-card-default" hidden>
  <div class="uk-card-header">
    <div class="uk-grid-small uk-flex-middle" uk-grid>
      <div class="uk-width-auto">
        <img class='image uk-border-circle'>
      </div>
      <div class="uk-width-expand">
          <p class="uk-margin-remove-bottom username"></p>
          <p class="uk-text-meta uk-margin-remove-top created"></p>
      </div>
    </div>
  </div>

  <div class="uk-card-body uk-padding-small">
    <p class="content"></p>
  </div>
</div>

<br>